-- 7. What is the total revenue generated by the sales of hatchback cars?
SELECT
     c.style
   , SUM(c.cost_$) AS total_revenue
FROM
   cars AS c
INNER JOIN
   sales AS s
   ON
     c.car_id = s.car_id
WHERE
   style = 'Hatchback';
