-- 5. What is the total revenue generated by each car type?
SELECT
    c.car_id
  , c.type
  , SUM(c.cost_$) AS total_revenue_by_car
FROM
  cars AS c
INNER JOIN
  sales AS s
  ON
    s.car_id = c.car_id
GROUP BY
  s.car_id
ORDER BY
  c.car_id;
