-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT
    c.style
  , SUM(c.cost_$) AS total_revenue
FROM
  cars AS c
INNER JOIN
  sales AS s
  ON
    c.car_id = s.car_id
WHERE
  c.style = 'SUV'
  AND
  YEAR(s.purchase_date) = '2022'
